### ISSUE TITLE
App crashes after speech getting recognized

### ISSUE THREAD

**Issue by viktapas** [vikaskumar-vsk/SpeechToText_master#1]
**Here is the catlog:**

```
03-31 19:49:36.392 23286-23286/labs.ika.stt E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: labs.ika.stt, PID: 23286
                                                              java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { (has extras) }} to activity {labs.ika.stt/labs.ika.stt.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                  at android.app.ActivityThread.deliverResults(ActivityThread.java:4104)
                                                                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:4147)
                                                                  at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6169)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                  at labs.ika.stt.MainActivity.onActivityResult(MainActivity.java:94)
                                                                  at android.app.Activity.dispatchActivityResult(Activity.java:6982)
                                                                  at android.app.ActivityThread.deliverResults(ActivityThread.java:4100)
                                                                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:4147) 
                                                                  at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6169) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 

```

**Comment by viktapas** [comment]
Adding `TextView text = (TextView)findViewById(R.id.tab1text);` in `codeline 91` of `MainActivity.java` fixes the crash.
